import numpy as np

from ._base_class import BaseEstimationMethod, BasePermutationTest
from ..test_functions.ac_coefficient import ac_coefficient


class _ACMixin:
    def _ac_statistic(self, Z, Y):
        return ac_coefficient(
            Y=Y,
            Z=Z,
            X=self.X if not self._ignore_X else None,
            M=self.M,
            rng=self.rng,
            aggregate=self.aggregate_coeff,
            permutation=self.use_permutation_coeff,
            right_neighbor=self.use_right_neighbor,
            block_size=self.block_size,
        )

    def _adaptive_s_statistic(self, Z, Y, M):
        """Return the coefficient xi_M(Y, Z) for one M."""
        return ac_coefficient(
            Y=Y,
            Z=Z,
            X=self.X if not self._ignore_X else None,
            M=M,
            rng=self.rng,
            aggregate=None,
            permutation=self.use_permutation_coeff,
            right_neighbor=self.use_right_neighbor,
            block_size=self.block_size,
        )


class EstimateAC(_ACMixin, BaseEstimationMethod):
    """Estimate the AC coefficient between network latent Z and observed Y."""

    def __init__(
        self,
        rng=None,
        solver=None,
        k=None,
        use_true_latent=False,
        M=None,
        aggregate_coeff=None,
        use_permutation_coeff=False,
        use_right_neighbor=False,
        block_size=2048,
        **kwargs,
    ):
        super().__init__(
            k=k, rng=rng, solver=solver, use_true_latent=use_true_latent
        )
        self.M = M
        self.aggregate_coeff = aggregate_coeff
        self.use_permutation_coeff = use_permutation_coeff
        self.use_right_neighbor = use_right_neighbor
        self.block_size = block_size
        self._ignore_X = False

    def fit(self, data, **kwargs):
        self._process_input(data)
        self.test_stat_estimate = self._ac_statistic(self.Zhat, self.Y)
        self.pvalue = None
        self.reject_null = None

    def get_name(self):
        return "EstimateAC"


class MultivariateACTest(_ACMixin, BasePermutationTest):
    """Permutation test using fixed-M or adaptive AC coefficients.

    With ``adaptive_m=True``, ``M`` and ``aggregate_coeff`` are ignored. The
    test uses the rounded, capped, and deduplicated grid generated by
    exponents 0.3, 0.5, 0.7, and 0.9. At each grid value it computes the
    coefficient for Y, which may be univariate or multivariate. All other
    coefficient and permutation options retain their usual behavior.
    """

    _ADAPTIVE_EXPONENTS = (0.3, 0.5, 0.7, 0.9)

    def __init__(
        self,
        k=None,
        M=None,
        npermutations=100,
        alpha=0.05,
        rng=None,
        solver=None,
        use_true_latent=False,
        permutation_type="covariate",
        aggregate_coeff=None,
        use_permutation_coeff=False,
        use_right_neighbor=False,
        adaptive_m=False,
        block_size=2048,
        _ignore_X=False, # temp for testing
        **kwargs,
    ):
        self.M = M
        self.aggregate_coeff = aggregate_coeff
        self.use_permutation_coeff = use_permutation_coeff
        self.use_right_neighbor = use_right_neighbor
        self.adaptive_m = bool(adaptive_m)
        self.block_size = block_size
        self._ignore_X = _ignore_X
        super().__init__(
            k=k,
            npermutations=npermutations,
            alpha=alpha,
            use_true_latent=use_true_latent,
            permutation_type=permutation_type,
            solver=solver,
            test_function=self._ac_statistic,
            rng=rng,
            stratify_permutations=not _ignore_X,
            one_sided=True,
        )

    def fit(self, data, **kwargs):
        self._process_input(data)
        if self.adaptive_m:
            self._fit_adaptive_permutation()
        else:
            self._fit_permutation()

    @classmethod
    def _adaptive_m_grid(cls, n):
        """Return the rounded, capped, and deduplicated adaptive M grid."""
        capped = (
            min(round(n**exponent), n - 1)
            for exponent in cls._ADAPTIVE_EXPONENTS
        )
        return np.asarray(list(dict.fromkeys(capped)), dtype=int)

    def _adaptive_statistics(self, Z, Y):
        return np.asarray(
            [self._adaptive_s_statistic(Z, Y, M) for M in self.adaptive_m_values],
            dtype=float,
        )

    def _fit_adaptive_permutation(self):
        if self.npermutations < 1:
            raise ValueError(
                "Adaptive M selection requires at least one permutation to "
                "compute sample standard deviations."
            )

        self.adaptive_m_values = self._adaptive_m_grid(self.Y.shape[0])
        statistic_rows = [self._adaptive_statistics(self.Zhat, self.Y)]
        self.permutation_indices = []

        for _ in range(self.npermutations):
            perm = self._draw_permutation()
            self.permutation_indices.append(perm.copy())

            if self.permutation_type == "covariate":
                Z_stat, Y_stat = self.Zhat, self.Y[perm, :]
            elif self.permutation_type == "latent":
                Z_stat, Y_stat = self.Zhat[perm, :], self.Y
            else:
                if self.A is None:
                    raise ValueError("A is required for observed permutations.")
                A_perm = self.A[perm][:, perm]
                Z_stat = self.solver(A_perm, k=self.k, rng=self.rng)[0]
                Y_stat = self.Y

            statistic_rows.append(self._adaptive_statistics(Z_stat, Y_stat))

        self.adaptive_s_statistics = np.vstack(statistic_rows)
        self.adaptive_m_means = self.adaptive_s_statistics.mean(axis=0)
        self.adaptive_m_stds = self.adaptive_s_statistics.std(axis=0, ddof=1)

        zero_std = self.adaptive_m_stds == 0
        if np.any(zero_std):
            zero_m = self.adaptive_m_values[zero_std].tolist()
            raise ValueError(
                f"Adaptive M standard deviation is zero for M={zero_m}."
            )

        self.adaptive_z_statistics = (
            self.adaptive_s_statistics - self.adaptive_m_means
        ) / self.adaptive_m_stds
        adaptive_statistics = self.adaptive_z_statistics.max(axis=1)

        self.test_stat_estimate = float(adaptive_statistics[0])
        self.permutation_distribution = adaptive_statistics[1:].tolist()
        exceedances = np.count_nonzero(
            adaptive_statistics[1:] >= self.test_stat_estimate
        )
        self.pvalue = float((1 + exceedances) / (self.npermutations + 1))
        self.reject_null = bool(self.pvalue < self.alpha)

    def get_name(self):
        if self.adaptive_m:
            statistic_description = "adaptive"
        else:
            statistic_description = f"{self.M}_{self.aggregate_coeff}"

        name = (
            "MultivariateAC_PermutationTest_"
            f"{self.permutation_type}_{statistic_description}"
        )
        if self._ignore_X:
            name += "_ignoreX"
        return name
