import numpy as np

from ._base_class import BaseEstimationMethod, BasePermutationTest
from ..test_functions.ac_coefficient import ac_coefficient


class _ACMixin:
    def _ac_statistic(self, Z, Y, rng=None):
        rng = self.rng if rng is None else rng
        return ac_coefficient(
            Y=Y,
            Z=Z,
            X=self.X if not self._ignore_X else None,
            M=self.M,
            rng=rng,
            permutation=self.use_permutation_coeff,
            right_neighbor=self.use_right_neighbor,
            block_size=self.block_size,
        )

    def _adaptive_s_statistic(self, Z, Y, M, rng=None):
        """Return the coefficient xi_M(Y, Z) for one M."""
        rng = self.rng if rng is None else rng
        return ac_coefficient(
            Y=Y,
            Z=Z,
            X=self.X if not self._ignore_X else None,
            M=M,
            rng=rng,
            permutation=self.use_permutation_coeff,
            right_neighbor=self.use_right_neighbor,
            block_size=self.block_size,
        )


class EstimateAC(_ACMixin, BaseEstimationMethod):
    """Estimate the AC coefficient between network latent Z and observed Y."""

    def __init__(
        self,
        rng=None,
        solver=None,
        k=None,
        use_true_latent=False,
        M=None,
        use_permutation_coeff=False,
        use_right_neighbor=False,
        block_size=2048,
        **kwargs,
    ):
        super().__init__(
            k=k, rng=rng, solver=solver, use_true_latent=use_true_latent
        )
        self.M = M
        self.use_permutation_coeff = use_permutation_coeff
        self.use_right_neighbor = use_right_neighbor
        self.block_size = block_size
        self._ignore_X = False

    def fit(self, data, **kwargs):
        self._process_input(data)
        self.test_stat_estimate = self._ac_statistic(self.Zhat, self.Y)
        self.pvalue = None
        self.reject_null = None

    def get_name(self):
        return "EstimateAC"


class MultivariateACTest(_ACMixin, BasePermutationTest):
    """Permutation test using fixed-M or adaptive AC coefficients.

    With ``adaptive_m=True``, ``M`` is ignored. The test uses the rounded,
    capped, and deduplicated grid generated by
    exponents 0.3, 0.5, 0.7, and 0.9. At each grid value it computes the
    coefficient for Y, which may be univariate or multivariate. All other
    coefficient and permutation options retain their usual behavior.
    """

    _ADAPTIVE_EXPONENTS = (0.3, 0.5, 0.7, 0.9)

    def __init__(
        self,
        k=None,
        M=None,
        npermutations=100,
        alpha=0.05,
        rng=None,
        solver=None,
        use_true_latent=False,
        permutation_type="covariate",
        use_permutation_coeff=False,
        use_right_neighbor=False,
        adaptive_m=False,
        block_size=2048,
        n_jobs=1,
        batch_size=32,
        verbose=False,
        _ignore_X=False, # temp for testing
        **kwargs,
    ):
        self.M = M
        self.use_permutation_coeff = use_permutation_coeff
        self.use_right_neighbor = use_right_neighbor
        self.adaptive_m = bool(adaptive_m)
        self.block_size = block_size
        self._ignore_X = _ignore_X
        super().__init__(
            k=k,
            npermutations=npermutations,
            alpha=alpha,
            use_true_latent=use_true_latent,
            permutation_type=permutation_type,
            solver=solver,
            test_function=self._ac_statistic,
            rng=rng,
            stratify_permutations=not _ignore_X,
            one_sided=True,
            n_jobs=n_jobs,
            batch_size=batch_size,
            verbose=verbose,
        )

    def fit(self, data, **kwargs):
        self._process_input(data)
        if self.adaptive_m:
            if self.npermutations < 1:
                raise ValueError(
                    "Adaptive M selection requires at least one permutation to "
                    "compute sample standard deviations."
                )
            self.adaptive_m_values = self._adaptive_m_grid(self.Y.shape[0])
        self._fit_permutation()

        if self.adaptive_m:
            self.adaptive_s_statistics = self.statistic_matrix
            self.adaptive_m_means = self.statistic_means
            self.adaptive_m_stds = self.statistic_standard_deviations
            self.adaptive_z_statistics = self.standardized_statistics

    @classmethod
    def _adaptive_m_grid(cls, n):
        """Return the rounded, capped, and deduplicated adaptive M grid."""
        capped = (
            min(round(n**exponent), n - 1)
            for exponent in cls._ADAPTIVE_EXPONENTS
        )
        return np.asarray(list(dict.fromkeys(capped)), dtype=int)

    def _adaptive_statistics(self, Z, Y, rng=None):
        return np.asarray(
            [
                self._adaptive_s_statistic(Z, Y, M, rng=rng)
                for M in self.adaptive_m_values
            ],
            dtype=float,
        )

    def _evaluate_test_statistic(self, Z, Y, rng):
        if self.adaptive_m:
            return self._adaptive_statistics(Z, Y, rng=rng)
        return self._ac_statistic(Z, Y, rng=rng)

    def get_name(self):
        if self.adaptive_m:
            statistic_description = "adaptive"
        else:
            statistic_description = str(self.M)

        name = (
            "MultivariateAC_PermutationTest_"
            f"{self.permutation_type}_{statistic_description}"
        )
        if self._ignore_X:
            name += "_ignoreX"
        return name
